/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerRouteImport } from './routes/server'
import { Route as LogRouteImport } from './routes/log'

const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/log': typeof LogRoute
  '/server': typeof ServerRoute
}
export interface FileRoutesByTo {
  '/log': typeof LogRoute
  '/server': typeof ServerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/log': typeof LogRoute
  '/server': typeof ServerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/log' | '/server'
  fileRoutesByTo: FileRoutesByTo
  to: '/log' | '/server'
  id: '__root__' | '/log' | '/server'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LogRoute: typeof LogRoute
  ServerRoute: typeof ServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LogRoute: LogRoute,
  ServerRoute: ServerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
