/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PickerRouteImport } from './routes/picker'
import { Route as GamePathRouteImport } from './routes/game.$path'

const PickerRoute = PickerRouteImport.update({
  id: '/picker',
  path: '/picker',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePathRoute = GamePathRouteImport.update({
  id: '/game/$path',
  path: '/game/$path',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/picker': typeof PickerRoute
  '/game/$path': typeof GamePathRoute
}
export interface FileRoutesByTo {
  '/picker': typeof PickerRoute
  '/game/$path': typeof GamePathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/picker': typeof PickerRoute
  '/game/$path': typeof GamePathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/picker' | '/game/$path'
  fileRoutesByTo: FileRoutesByTo
  to: '/picker' | '/game/$path'
  id: '__root__' | '/picker' | '/game/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PickerRoute: typeof PickerRoute
  GamePathRoute: typeof GamePathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/picker': {
      id: '/picker'
      path: '/picker'
      fullPath: '/picker'
      preLoaderRoute: typeof PickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$path': {
      id: '/game/$path'
      path: '/game/$path'
      fullPath: '/game/$path'
      preLoaderRoute: typeof GamePathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PickerRoute: PickerRoute,
  GamePathRoute: GamePathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
